config/routes.rb
Diaphanum::Application.routes.draw do
  resources :layer_categories

  resources :dictionaries

  resources :layers

  resources :municipios

  resources :casens

  get "filter" => "analyses#filter"

  match "export" => "analyses#export"

   root :to => 'static#map'

end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
  attr_accessible :asiste_mean, :asiste_median, :asiste_standard_deviation, :comuna, :e6a_mode, :e7_mean, :e7_median, :e7_mode, :e7_standard_deviation, :ecivil_mode, :edad_mean, :edad_median, :edad_standard_deviation, :educ_mean, :educ_median, :educ_mode, :educ_standard_deviation, :name, :nucleo_mean, :nucleo_median, :nucleo_standard_deviation, :numper_mean, :numper_median, :numper_standard_deviation, :pco2_mode, :population, :hombre_percentage, :mujer_percentage, :soltero_percentage, :soltera_percentage, :casado_percentage, :casada_percentage, :emparejado_percentage, :emparejada_percentage, :tot_hogviv_mean, :y29a_percentage, :y29b1_percentage, :y29b2_percentage, :y29b3_percentage, :y29b4_percentage, :y20a_percentage, :y30b_percentage, :y30c_percentage, :y30d_percentage, :y30e_percentage, :corte_percentage, :qaut_mean, :daut_mean, :yataj_mean, :yathaj_mean, :ytotaj_mean, :ytothaj_mean, :ymoneaj_mean, :yaimhaj_mean, :r10_percentage, :r11a_percentage, :r11b_percentage, :r12_percentage, :r13a_percentage, :r13b_percentage, :r13c_percentage, :r13d_percentage, :r13e_percentage, :r13f_percentage, :r14a_percentage, :r14b_percentage, :r14c_percentage, :r14d_percentage, :r14e_percentage, :r16_mode, :r17_mean, :r18b_percentage, :r18c_percentage, :r18d_percentage, :r18e_percentage, :r18f_percentage, :r18g_percentage, :r18h_percentage, :r19_percentage, :r20_mean, :v1_mean, :v2_mean, :v2frent_mean, :v2fo_mean, :v3_percentage , :v4_percentage , :v5_mean, :v5m_mean
  has_many :casens, :class_name => 'Casen', :primary_key => 'comuna', :foreign_key => 'comuna'

end

app/controllers/municipios_controller.rb
class MunicipiosController < ApplicationController
  # GET /municipios
  # GET /municipios.json
  def index
    @municipios = Municipio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @municipios }
    end
  end

  # GET /municipios/1
  # GET /municipios/1.json
  def show
    @municipio = Municipio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @municipio }
    end
  end

  # GET /municipios/new
  # GET /municipios/new.json
  def new
    @municipio = Municipio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @municipio }
    end
  end

  # GET /municipios/1/edit
  def edit
    @municipio = Municipio.find(params[:id])
  end

  # POST /municipios
  # POST /municipios.json
  def create
    @municipio = Municipio.new(params[:municipio])

    respond_to do |format|
      if @municipio.save
        format.html { redirect_to @municipio, notice: 'Municipio was successfully created.' }
        format.json { render json: @municipio, status: :created, location: @municipio }
      else
        format.html { render action: "new" }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /municipios/1
  # PUT /municipios/1.json
  def update
    @municipio = Municipio.find(params[:id])

    respond_to do |format|
      if @municipio.update_attributes(params[:municipio])
        format.html { redirect_to @municipio, notice: 'Municipio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipios/1
  # DELETE /municipios/1.json
  def destroy
    @municipio = Municipio.find(params[:id])
    @municipio.destroy

    respond_to do |format|
      format.html { redirect_to municipios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/views/municipios/_form.html.erb
<%= form_for(@municipio) do |f| %>
  <% if @municipio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@municipio.errors.count, "error") %> prohibited this municipio from being saved:</h2>

      <ul>
      <% @municipio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comuna %><br />
    <%= f.number_field :comuna %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :population %><br />
    <%= f.number_field :population %>
  </div>
  <div class="field">
    <%= f.label :edad_mean %><br />
    <%= f.text_field :edad_mean %>
  </div>
  <div class="field">
    <%= f.label :edad_median %><br />
    <%= f.text_field :edad_median %>
  </div>
  <div class="field">
    <%= f.label :edad_standard_deviation %><br />
    <%= f.text_field :edad_standard_deviation %>
  </div>
  <div class="field">
    <%= f.label :ecivil_mode %><br />
    <%= f.text_field :ecivil_mode %>
  </div>
  <div class="field">
    <%= f.label :nucleo_mean %><br />
    <%= f.text_field :nucleo_mean %>
  </div>
  <div class="field">
    <%= f.label :nucleo_median %><br />
    <%= f.text_field :nucleo_median %>
  </div>
  <div class="field">
    <%= f.label :nucleo_standard_deviation %><br />
    <%= f.text_field :nucleo_standard_deviation %>
  </div>
  <div class="field">
    <%= f.label :pco2_mode %><br />
    <%= f.text_field :pco2_mode %>
  </div>
  <div class="field">
    <%= f.label :numper_mean %><br />
    <%= f.text_field :numper_mean %>
  </div>
  <div class="field">
    <%= f.label :numper_median %><br />
    <%= f.text_field :numper_median %>
  </div>
  <div class="field">
    <%= f.label :numper_standard_deviation %><br />
    <%= f.text_field :numper_standard_deviation %>
  </div>
  <div class="field">
    <%= f.label :e6a_mode %><br />
    <%= f.text_field :e6a_mode %>
  </div>
  <div class="field">
    <%= f.label :e7_mean %><br />
    <%= f.text_field :e7_mean %>
  </div>
  <div class="field">
    <%= f.label :e7_median %><br />
    <%= f.text_field :e7_median %>
  </div>
  <div class="field">
    <%= f.label :e7_standard_deviation %><br />
    <%= f.text_field :e7_standard_deviation %>
  </div>
  <div class="field">
    <%= f.label :e7_mode %><br />
    <%= f.text_field :e7_mode %>
  </div>
  <div class="field">
    <%= f.label :educ_mean %><br />
    <%= f.text_field :educ_mean %>
  </div>
  <div class="field">
    <%= f.label :educ_median %><br />
    <%= f.text_field :educ_median %>
  </div>
  <div class="field">
    <%= f.label :educ_standard_deviation %><br />
    <%= f.text_field :educ_standard_deviation %>
  </div>
  <div class="field">
    <%= f.label :educ_mode %><br />
    <%= f.text_field :educ_mode %>
  </div>
  <div class="field">
    <%= f.label :asiste_mean %><br />
    <%= f.text_field :asiste_mean %>
  </div>
  <div class="field">
    <%= f.label :asiste_median %><br />
    <%= f.text_field :asiste_median %>
  </div>
  <div class="field">
    <%= f.label :asiste_standard_deviation %><br />
    <%= f.text_field :asiste_standard_deviation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/municipios/edit.html.erb
<h1>Editing municipio</h1>

<%= render 'form' %>

<%= link_to 'Show', @municipio %> |
<%= link_to 'Back', municipios_path %>

app/views/municipios/index.html.erb
<h1>Listing municipios</h1>

<table>
  <tr>
    <th>Comuna</th>
    <th>Name</th>
    <th>Population</th>
    <th>Edad mean</th>
    <th>Edad median</th>
    <th>Edad standard deviation</th>
    <th>Ecivil mode</th>
    <th>Nucleo mean</th>
    <th>Nucleo median</th>
    <th>Nucleo standard deviation</th>
    <th>Pco2 mode</th>
    <th>Numper mean</th>
    <th>Numper median</th>
    <th>Numper standard deviation</th>
    <th>E6a mode</th>
    <th>E7 mean</th>
    <th>E7 median</th>
    <th>E7 standard deviation</th>
    <th>E7 mode</th>
    <th>Educ mean</th>
    <th>Educ median</th>
    <th>Educ standard deviation</th>
    <th>Educ mode</th>
    <th>Asiste mean</th>
    <th>Asiste median</th>
    <th>Asiste standard deviation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @municipios.each do |municipio| %>
  <tr>
    <td><%= municipio.comuna %></td>
    <td><%= municipio.name %></td>
    <td><%= municipio.population %></td>
    <td><%= municipio.edad_mean %></td>
    <td><%= municipio.edad_median %></td>
    <td><%= municipio.edad_standard_deviation %></td>
    <td><%= municipio.ecivil_mode %></td>
    <td><%= municipio.nucleo_mean %></td>
    <td><%= municipio.nucleo_median %></td>
    <td><%= municipio.nucleo_standard_deviation %></td>
    <td><%= municipio.pco2_mode %></td>
    <td><%= municipio.numper_mean %></td>
    <td><%= municipio.numper_median %></td>
    <td><%= municipio.numper_standard_deviation %></td>
    <td><%= municipio.e6a_mode %></td>
    <td><%= municipio.e7_mean %></td>
    <td><%= municipio.e7_median %></td>
    <td><%= municipio.e7_standard_deviation %></td>
    <td><%= municipio.e7_mode %></td>
    <td><%= municipio.educ_mean %></td>
    <td><%= municipio.educ_median %></td>
    <td><%= municipio.educ_standard_deviation %></td>
    <td><%= municipio.educ_mode %></td>
    <td><%= municipio.asiste_mean %></td>
    <td><%= municipio.asiste_median %></td>
    <td><%= municipio.asiste_standard_deviation %></td>
    <td><%= link_to 'Show', municipio %></td>
    <td><%= link_to 'Edit', edit_municipio_path(municipio) %></td>
    <td><%= link_to 'Destroy', municipio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Municipio', new_municipio_path %>

app/views/municipios/new.html.erb
<h1>New municipio</h1>

<%= render 'form' %>

<%= link_to 'Back', municipios_path %>

app/views/municipios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comuna:</b>
  <%= @municipio.comuna %>
</p>

<p>
  <b>Name:</b>
  <%= @municipio.name %>
</p>

<p>
  <b>Population:</b>
  <%= @municipio.population %>
</p>

<p>
  <b>Edad mean:</b>
  <%= @municipio.edad_mean %>
</p>

<p>
  <b>Edad median:</b>
  <%= @municipio.edad_median %>
</p>

<p>
  <b>Edad standard deviation:</b>
  <%= @municipio.edad_standard_deviation %>
</p>

<p>
  <b>Ecivil mode:</b>
  <%= @municipio.ecivil_mode %>
</p>

<p>
  <b>Nucleo mean:</b>
  <%= @municipio.nucleo_mean %>
</p>

<p>
  <b>Nucleo median:</b>
  <%= @municipio.nucleo_median %>
</p>

<p>
  <b>Nucleo standard deviation:</b>
  <%= @municipio.nucleo_standard_deviation %>
</p>

<p>
  <b>Pco2 mode:</b>
  <%= @municipio.pco2_mode %>
</p>

<p>
  <b>Numper mean:</b>
  <%= @municipio.numper_mean %>
</p>

<p>
  <b>Numper median:</b>
  <%= @municipio.numper_median %>
</p>

<p>
  <b>Numper standard deviation:</b>
  <%= @municipio.numper_standard_deviation %>
</p>

<p>
  <b>E6a mode:</b>
  <%= @municipio.e6a_mode %>
</p>

<p>
  <b>E7 mean:</b>
  <%= @municipio.e7_mean %>
</p>

<p>
  <b>E7 median:</b>
  <%= @municipio.e7_median %>
</p>

<p>
  <b>E7 standard deviation:</b>
  <%= @municipio.e7_standard_deviation %>
</p>

<p>
  <b>E7 mode:</b>
  <%= @municipio.e7_mode %>
</p>

<p>
  <b>Educ mean:</b>
  <%= @municipio.educ_mean %>
</p>

<p>
  <b>Educ median:</b>
  <%= @municipio.educ_median %>
</p>

<p>
  <b>Educ standard deviation:</b>
  <%= @municipio.educ_standard_deviation %>
</p>

<p>
  <b>Educ mode:</b>
  <%= @municipio.educ_mode %>
</p>

<p>
  <b>Asiste mean:</b>
  <%= @municipio.asiste_mean %>
</p>

<p>
  <b>Asiste median:</b>
  <%= @municipio.asiste_median %>
</p>

<p>
  <b>Asiste standard deviation:</b>
  <%= @municipio.asiste_standard_deviation %>
</p>


<%= link_to 'Edit', edit_municipio_path(@municipio) %> |
<%= link_to 'Back', municipios_path %>