config/routes.rb
Diaphanum::Application.routes.draw do
  resources :layer_categories

  resources :dictionaries

  resources :layers

  resources :municipios

  resources :casens

  get "filter" => "analyses#filter"

  match "export" => "analyses#export"

   root :to => 'static#map'

end

app/models/layer_category.rb
class LayerCategory < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :dictionaries
  has_many :layers
end

app/controllers/layer_categories_controller.rb
class LayerCategoriesController < ApplicationController
  # GET /layer_categories
  # GET /layer_categories.json
  def index
    @layer_categories = LayerCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json #{ render json: @layer_categories }
    end
  end

  # GET /layer_categories/1
  # GET /layer_categories/1.json
  def show
    @layer_category = LayerCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json #{ render json: @layer_category }
    end
  end

  # GET /layer_categories/new
  # GET /layer_categories/new.json
  def new
    @layer_category = LayerCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @layer_category }
    end
  end

  # GET /layer_categories/1/edit
  def edit
    @layer_category = LayerCategory.find(params[:id])
  end

  # POST /layer_categories
  # POST /layer_categories.json
  def create
    @layer_category = LayerCategory.new(params[:layer_category])

    respond_to do |format|
      if @layer_category.save
        format.html { redirect_to @layer_category, notice: 'Layer category was successfully created.' }
        format.json { render json: @layer_category, status: :created, location: @layer_category }
      else
        format.html { render action: "new" }
        format.json { render json: @layer_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /layer_categories/1
  # PUT /layer_categories/1.json
  def update
    @layer_category = LayerCategory.find(params[:id])

    respond_to do |format|
      if @layer_category.update_attributes(params[:layer_category])
        format.html { redirect_to @layer_category, notice: 'Layer category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @layer_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /layer_categories/1
  # DELETE /layer_categories/1.json
  def destroy
    @layer_category = LayerCategory.find(params[:id])
    @layer_category.destroy

    respond_to do |format|
      format.html { redirect_to layer_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/layer_categories_helper.rb
module LayerCategoriesHelper
end

app/views/layer_categories/_form.html.erb
<%= form_for(@layer_category) do |f| %>
  <% if @layer_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@layer_category.errors.count, "error") %> prohibited this layer_category from being saved:</h2>

      <ul>
      <% @layer_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layer_categories/edit.html.erb
<h1>Editing layer_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @layer_category %> |
<%= link_to 'Back', layer_categories_path %>

app/views/layer_categories/index.html.erb
<h1>Listing layer_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @layer_categories.each do |layer_category| %>
  <tr>
    <td><%= layer_category.name %></td>
    <td><%= layer_category.description %></td>
    <td><%= link_to 'Show', layer_category %></td>
    <td><%= link_to 'Edit', edit_layer_category_path(layer_category) %></td>
    <td><%= link_to 'Destroy', layer_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Layer category', new_layer_category_path %>

app/views/layer_categories/new.html.erb
<h1>New layer_category</h1>

<%= render 'form' %>

<%= link_to 'Back', layer_categories_path %>

app/views/layer_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @layer_category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @layer_category.description %>
</p>


<%= link_to 'Edit', edit_layer_category_path(@layer_category) %> |
<%= link_to 'Back', layer_categories_path %>