config/routes.rb
Diaphanum::Application.routes.draw do
  resources :layer_categories

  resources :dictionaries

  resources :layers

  resources :municipios

  resources :casens

  get "filter" => "analyses#filter"

  match "export" => "analyses#export"

   root :to => 'static#map'

end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
  attr_accessible :comment, :label, :variable, :layer_category_id
  belongs_to :layer_category
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dictionaries }
    end
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
    @dictionary = Dictionary.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dictionary }
    end
  end

  # GET /dictionaries/new
  # GET /dictionaries/new.json
  def new
    @dictionary = Dictionary.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dictionary }
    end
  end

  # GET /dictionaries/1/edit
  def edit
    @dictionary = Dictionary.find(params[:id])
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(params[:dictionary])

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render json: @dictionary, status: :created, location: @dictionary }
      else
        format.html { render action: "new" }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dictionaries/1
  # PUT /dictionaries/1.json
  def update
    @dictionary = Dictionary.find(params[:id])

    respond_to do |format|
      if @dictionary.update_attributes(params[:dictionary])
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary = Dictionary.find(params[:id])
    @dictionary.destroy

    respond_to do |format|
      format.html { redirect_to dictionaries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_form.html.erb
<%= form_for(@dictionary) do |f| %>
  <% if @dictionary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dictionary.errors.count, "error") %> prohibited this dictionary from being saved:</h2>

      <ul>
      <% @dictionary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :variable %><br />
    <%= f.text_field :variable %>
  </div>
  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dictionaries/edit.html.erb
<h1>Editing dictionary</h1>

<%= render 'form' %>

<%= link_to 'Show', @dictionary %> |
<%= link_to 'Back', dictionaries_path %>

app/views/dictionaries/index.html.erb
<h1>Listing dictionaries</h1>

<table>
  <tr>
    <th>Variable</th>
    <th>Label</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dictionaries.each do |dictionary| %>
  <tr>
    <td><%= dictionary.variable %></td>
    <td><%= dictionary.label %></td>
    <td><%= dictionary.comment %></td>
    <td><%= link_to 'Show', dictionary %></td>
    <td><%= link_to 'Edit', edit_dictionary_path(dictionary) %></td>
    <td><%= link_to 'Destroy', dictionary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dictionary', new_dictionary_path %>

app/views/dictionaries/new.html.erb
<h1>New dictionary</h1>

<%= render 'form' %>

<%= link_to 'Back', dictionaries_path %>

app/views/dictionaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Variable:</b>
  <%= @dictionary.variable %>
</p>

<p>
  <b>Label:</b>
  <%= @dictionary.label %>
</p>

<p>
  <b>Comment:</b>
  <%= @dictionary.comment %>
</p>


<%= link_to 'Edit', edit_dictionary_path(@dictionary) %> |
<%= link_to 'Back', dictionaries_path %>