config/routes.rb
Diaphanum::Application.routes.draw do
  resources :layer_categories

  resources :dictionaries

  resources :layers

  resources :municipios

  resources :casens

  get "filter" => "analyses#filter"

  match "export" => "analyses#export"

   root :to => 'static#map'

end

app/models/layer.rb
class Layer < ActiveRecord::Base
  attr_accessible :description, :maxValue, :minValue, :name, :opacity, :show, :style, :title, :variable, :layer_category_id
  belongs_to :layer_category
end

app/controllers/layers_controller.rb
class LayersController < ApplicationController
  # GET /layers
  # GET /layers.json
  def index
    @layers = Layer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json #{ render json: @layers }
    end
  end

  # GET /layers/1
  # GET /layers/1.json
  def show
    @layer = Layer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json #{ render json: @layer }
    end
  end

  # GET /layers/new
  # GET /layers/new.json
  def new
    @layer = Layer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @layer }
    end
  end

  # GET /layers/1/edit
  def edit
    @layer = Layer.find(params[:id])
  end

  # POST /layers
  # POST /layers.json
  def create
    @layer = Layer.new(params[:layer])

    respond_to do |format|
      if @layer.save
        format.html { redirect_to @layer, notice: 'Layer was successfully created.' }
        format.json { render json: @layer, status: :created, location: @layer }
      else
        format.html { render action: "new" }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /layers/1
  # PUT /layers/1.json
  def update
    @layer = Layer.find(params[:id])

    respond_to do |format|
      if @layer.update_attributes(params[:layer])
        format.html { redirect_to @layer, notice: 'Layer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /layers/1
  # DELETE /layers/1.json
  def destroy
    @layer = Layer.find(params[:id])
    @layer.destroy

    respond_to do |format|
      format.html { redirect_to layers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/layers_helper.rb
module LayersHelper
end

app/views/layers/_form.html.erb
<%= form_for(@layer) do |f| %>
  <% if @layer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@layer.errors.count, "error") %> prohibited this layer from being saved:</h2>

      <ul>
      <% @layer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :maxValue %><br />
    <%= f.text_field :maxValue %>
  </div>
  <div class="field">
    <%= f.label :minValue %><br />
    <%= f.text_field :minValue %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :opacity %><br />
    <%= f.text_field :opacity %>
  </div>
  <div class="field">
    <%= f.label :show %><br />
    <%= f.check_box :show %>
  </div>
  <div class="field">
    <%= f.label :style %><br />
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :variable %><br />
    <%= f.text_field :variable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layers/edit.html.erb
<h1>Editing layer</h1>

<%= render 'form' %>

<%= link_to 'Show', @layer %> |
<%= link_to 'Back', layers_path %>

app/views/layers/index.html.erb
<h1>Listing layers</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Maxvalue</th>
    <th>Minvalue</th>
    <th>Name</th>
    <th>Opacity</th>
    <th>Show</th>
    <th>Style</th>
    <th>Title</th>
    <th>Variable</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @layers.each do |layer| %>
  <tr>
    <td><%= layer.description %></td>
    <td><%= layer.maxValue %></td>
    <td><%= layer.minValue %></td>
    <td><%= layer.name %></td>
    <td><%= layer.opacity %></td>
    <td><%= layer.show %></td>
    <td><%= layer.style %></td>
    <td><%= layer.title %></td>
    <td><%= layer.variable %></td>
    <td><%= link_to 'Show', layer %></td>
    <td><%= link_to 'Edit', edit_layer_path(layer) %></td>
    <td><%= link_to 'Destroy', layer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Layer', new_layer_path %>

app/views/layers/new.html.erb
<h1>New layer</h1>

<%= render 'form' %>

<%= link_to 'Back', layers_path %>

app/views/layers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @layer.description %>
</p>

<p>
  <b>Maxvalue:</b>
  <%= @layer.maxValue %>
</p>

<p>
  <b>Minvalue:</b>
  <%= @layer.minValue %>
</p>

<p>
  <b>Name:</b>
  <%= @layer.name %>
</p>

<p>
  <b>Opacity:</b>
  <%= @layer.opacity %>
</p>

<p>
  <b>Show:</b>
  <%= @layer.show %>
</p>

<p>
  <b>Style:</b>
  <%= @layer.style %>
</p>

<p>
  <b>Title:</b>
  <%= @layer.title %>
</p>

<p>
  <b>Variable:</b>
  <%= @layer.variable %>
</p>


<%= link_to 'Edit', edit_layer_path(@layer) %> |
<%= link_to 'Back', layers_path %>